/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedWizardRouteImport } from './routes/_authenticated/wizard'
import { Route as AuthenticatedStudioBenchRouteImport } from './routes/_authenticated/studio-bench'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSoundpoolRouteImport } from './routes/_authenticated/soundpool'
import { Route as AuthenticatedSoundDesignerRouteImport } from './routes/_authenticated/sound-designer'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRemixRouteImport } from './routes/_authenticated/remix'
import { Route as AuthenticatedPartyHostRouteImport } from './routes/_authenticated/party-host'
import { Route as AuthenticatedMomentsRouteImport } from './routes/_authenticated/moments'
import { Route as AuthenticatedLyricWriterRouteImport } from './routes/_authenticated/lyric-writer'
import { Route as AuthenticatedLoopsRouteImport } from './routes/_authenticated/loops'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKaraokeRouteImport } from './routes/_authenticated/karaoke'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrowdRouteImport } from './routes/_authenticated/crowd'
import { Route as AuthenticatedCockpitRouteImport } from './routes/_authenticated/cockpit'
import { Route as AuthenticatedChoirRouteImport } from './routes/_authenticated/choir'
import { Route as AuthenticatedBattleRouteImport } from './routes/_authenticated/battle'
import { Route as AuthenticatedAutotuneRouteImport } from './routes/_authenticated/autotune'
import { Route as AuthenticatedAiLabRouteImport } from './routes/_authenticated/ai-lab'
import { Route as AuthenticatedFxIndexRouteImport } from './routes/_authenticated/fx/index'
import { Route as PPartyIdGuestRouteImport } from './routes/p.$partyId.guest'
import { Route as ApiAiPartyHostSpeakRouteImport } from './routes/api/ai/party-host-speak'
import { Route as AuthenticatedSettingsAudioRouteImport } from './routes/_authenticated/settings_.audio'
import { Route as AuthenticatedPartiesNewRouteImport } from './routes/_authenticated/parties.new'
import { Route as AuthenticatedPartiesPartyIdRouteImport } from './routes/_authenticated/parties.$partyId'
import { Route as AuthenticatedFxUploadRouteImport } from './routes/_authenticated/fx/upload'
import { Route as AuthenticatedFxFxIdRouteImport } from './routes/_authenticated/fx/$fxId'
import { Route as AuthenticatedAdminFxReviewRouteImport } from './routes/_authenticated/admin/fx-review'
import { Route as ApiPublicHooksStorageCleanupRouteImport } from './routes/api/public/hooks/storage-cleanup'

const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWizardRoute = AuthenticatedWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioBenchRoute =
  AuthenticatedStudioBenchRouteImport.update({
    id: '/studio-bench',
    path: '/studio-bench',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoundpoolRoute = AuthenticatedSoundpoolRouteImport.update({
  id: '/soundpool',
  path: '/soundpool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSoundDesignerRoute =
  AuthenticatedSoundDesignerRouteImport.update({
    id: '/sound-designer',
    path: '/sound-designer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemixRoute = AuthenticatedRemixRouteImport.update({
  id: '/remix',
  path: '/remix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartyHostRoute = AuthenticatedPartyHostRouteImport.update({
  id: '/party-host',
  path: '/party-host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMomentsRoute = AuthenticatedMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLyricWriterRoute =
  AuthenticatedLyricWriterRouteImport.update({
    id: '/lyric-writer',
    path: '/lyric-writer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoopsRoute = AuthenticatedLoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaraokeRoute = AuthenticatedKaraokeRouteImport.update({
  id: '/karaoke',
  path: '/karaoke',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrowdRoute = AuthenticatedCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCockpitRoute = AuthenticatedCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChoirRoute = AuthenticatedChoirRouteImport.update({
  id: '/choir',
  path: '/choir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleRoute = AuthenticatedBattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutotuneRoute = AuthenticatedAutotuneRouteImport.update({
  id: '/autotune',
  path: '/autotune',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiLabRoute = AuthenticatedAiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFxIndexRoute = AuthenticatedFxIndexRouteImport.update({
  id: '/fx/',
  path: '/fx/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PPartyIdGuestRoute = PPartyIdGuestRouteImport.update({
  id: '/p/$partyId/guest',
  path: '/p/$partyId/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPartyHostSpeakRoute = ApiAiPartyHostSpeakRouteImport.update({
  id: '/api/ai/party-host-speak',
  path: '/api/ai/party-host-speak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsAudioRoute =
  AuthenticatedSettingsAudioRouteImport.update({
    id: '/settings_/audio',
    path: '/settings/audio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartiesNewRoute = AuthenticatedPartiesNewRouteImport.update({
  id: '/parties/new',
  path: '/parties/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartiesPartyIdRoute =
  AuthenticatedPartiesPartyIdRouteImport.update({
    id: '/parties/$partyId',
    path: '/parties/$partyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFxUploadRoute = AuthenticatedFxUploadRouteImport.update({
  id: '/fx/upload',
  path: '/fx/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFxFxIdRoute = AuthenticatedFxFxIdRouteImport.update({
  id: '/fx/$fxId',
  path: '/fx/$fxId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFxReviewRoute =
  AuthenticatedAdminFxReviewRouteImport.update({
    id: '/admin/fx-review',
    path: '/admin/fx-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksStorageCleanupRoute =
  ApiPublicHooksStorageCleanupRouteImport.update({
    id: '/api/public/hooks/storage-cleanup',
    path: '/api/public/hooks/storage-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/visualizer': typeof VisualizerRoute
  '/ai-lab': typeof AuthenticatedAiLabRoute
  '/autotune': typeof AuthenticatedAutotuneRoute
  '/battle': typeof AuthenticatedBattleRoute
  '/choir': typeof AuthenticatedChoirRoute
  '/cockpit': typeof AuthenticatedCockpitRoute
  '/crowd': typeof AuthenticatedCrowdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/karaoke': typeof AuthenticatedKaraokeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/loops': typeof AuthenticatedLoopsRoute
  '/lyric-writer': typeof AuthenticatedLyricWriterRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/party-host': typeof AuthenticatedPartyHostRoute
  '/remix': typeof AuthenticatedRemixRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sound-designer': typeof AuthenticatedSoundDesignerRoute
  '/soundpool': typeof AuthenticatedSoundpoolRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/studio-bench': typeof AuthenticatedStudioBenchRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/admin/fx-review': typeof AuthenticatedAdminFxReviewRoute
  '/fx/$fxId': typeof AuthenticatedFxFxIdRoute
  '/fx/upload': typeof AuthenticatedFxUploadRoute
  '/parties/$partyId': typeof AuthenticatedPartiesPartyIdRoute
  '/parties/new': typeof AuthenticatedPartiesNewRoute
  '/settings/audio': typeof AuthenticatedSettingsAudioRoute
  '/api/ai/party-host-speak': typeof ApiAiPartyHostSpeakRoute
  '/p/$partyId/guest': typeof PPartyIdGuestRoute
  '/fx/': typeof AuthenticatedFxIndexRoute
  '/api/public/hooks/storage-cleanup': typeof ApiPublicHooksStorageCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/visualizer': typeof VisualizerRoute
  '/ai-lab': typeof AuthenticatedAiLabRoute
  '/autotune': typeof AuthenticatedAutotuneRoute
  '/battle': typeof AuthenticatedBattleRoute
  '/choir': typeof AuthenticatedChoirRoute
  '/cockpit': typeof AuthenticatedCockpitRoute
  '/crowd': typeof AuthenticatedCrowdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/karaoke': typeof AuthenticatedKaraokeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/loops': typeof AuthenticatedLoopsRoute
  '/lyric-writer': typeof AuthenticatedLyricWriterRoute
  '/moments': typeof AuthenticatedMomentsRoute
  '/party-host': typeof AuthenticatedPartyHostRoute
  '/remix': typeof AuthenticatedRemixRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sound-designer': typeof AuthenticatedSoundDesignerRoute
  '/soundpool': typeof AuthenticatedSoundpoolRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/studio-bench': typeof AuthenticatedStudioBenchRoute
  '/wizard': typeof AuthenticatedWizardRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/admin/fx-review': typeof AuthenticatedAdminFxReviewRoute
  '/fx/$fxId': typeof AuthenticatedFxFxIdRoute
  '/fx/upload': typeof AuthenticatedFxUploadRoute
  '/parties/$partyId': typeof AuthenticatedPartiesPartyIdRoute
  '/parties/new': typeof AuthenticatedPartiesNewRoute
  '/settings/audio': typeof AuthenticatedSettingsAudioRoute
  '/api/ai/party-host-speak': typeof ApiAiPartyHostSpeakRoute
  '/p/$partyId/guest': typeof PPartyIdGuestRoute
  '/fx': typeof AuthenticatedFxIndexRoute
  '/api/public/hooks/storage-cleanup': typeof ApiPublicHooksStorageCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/visualizer': typeof VisualizerRoute
  '/_authenticated/ai-lab': typeof AuthenticatedAiLabRoute
  '/_authenticated/autotune': typeof AuthenticatedAutotuneRoute
  '/_authenticated/battle': typeof AuthenticatedBattleRoute
  '/_authenticated/choir': typeof AuthenticatedChoirRoute
  '/_authenticated/cockpit': typeof AuthenticatedCockpitRoute
  '/_authenticated/crowd': typeof AuthenticatedCrowdRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/karaoke': typeof AuthenticatedKaraokeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/loops': typeof AuthenticatedLoopsRoute
  '/_authenticated/lyric-writer': typeof AuthenticatedLyricWriterRoute
  '/_authenticated/moments': typeof AuthenticatedMomentsRoute
  '/_authenticated/party-host': typeof AuthenticatedPartyHostRoute
  '/_authenticated/remix': typeof AuthenticatedRemixRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sound-designer': typeof AuthenticatedSoundDesignerRoute
  '/_authenticated/soundpool': typeof AuthenticatedSoundpoolRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/studio-bench': typeof AuthenticatedStudioBenchRoute
  '/_authenticated/wizard': typeof AuthenticatedWizardRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/admin/fx-review': typeof AuthenticatedAdminFxReviewRoute
  '/_authenticated/fx/$fxId': typeof AuthenticatedFxFxIdRoute
  '/_authenticated/fx/upload': typeof AuthenticatedFxUploadRoute
  '/_authenticated/parties/$partyId': typeof AuthenticatedPartiesPartyIdRoute
  '/_authenticated/parties/new': typeof AuthenticatedPartiesNewRoute
  '/_authenticated/settings_/audio': typeof AuthenticatedSettingsAudioRoute
  '/api/ai/party-host-speak': typeof ApiAiPartyHostSpeakRoute
  '/p/$partyId/guest': typeof PPartyIdGuestRoute
  '/_authenticated/fx/': typeof AuthenticatedFxIndexRoute
  '/api/public/hooks/storage-cleanup': typeof ApiPublicHooksStorageCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/visualizer'
    | '/ai-lab'
    | '/autotune'
    | '/battle'
    | '/choir'
    | '/cockpit'
    | '/crowd'
    | '/dashboard'
    | '/karaoke'
    | '/library'
    | '/loops'
    | '/lyric-writer'
    | '/moments'
    | '/party-host'
    | '/remix'
    | '/settings'
    | '/sound-designer'
    | '/soundpool'
    | '/studio'
    | '/studio-bench'
    | '/wizard'
    | '/api/transcribe'
    | '/admin/fx-review'
    | '/fx/$fxId'
    | '/fx/upload'
    | '/parties/$partyId'
    | '/parties/new'
    | '/settings/audio'
    | '/api/ai/party-host-speak'
    | '/p/$partyId/guest'
    | '/fx/'
    | '/api/public/hooks/storage-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/visualizer'
    | '/ai-lab'
    | '/autotune'
    | '/battle'
    | '/choir'
    | '/cockpit'
    | '/crowd'
    | '/dashboard'
    | '/karaoke'
    | '/library'
    | '/loops'
    | '/lyric-writer'
    | '/moments'
    | '/party-host'
    | '/remix'
    | '/settings'
    | '/sound-designer'
    | '/soundpool'
    | '/studio'
    | '/studio-bench'
    | '/wizard'
    | '/api/transcribe'
    | '/admin/fx-review'
    | '/fx/$fxId'
    | '/fx/upload'
    | '/parties/$partyId'
    | '/parties/new'
    | '/settings/audio'
    | '/api/ai/party-host-speak'
    | '/p/$partyId/guest'
    | '/fx'
    | '/api/public/hooks/storage-cleanup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/visualizer'
    | '/_authenticated/ai-lab'
    | '/_authenticated/autotune'
    | '/_authenticated/battle'
    | '/_authenticated/choir'
    | '/_authenticated/cockpit'
    | '/_authenticated/crowd'
    | '/_authenticated/dashboard'
    | '/_authenticated/karaoke'
    | '/_authenticated/library'
    | '/_authenticated/loops'
    | '/_authenticated/lyric-writer'
    | '/_authenticated/moments'
    | '/_authenticated/party-host'
    | '/_authenticated/remix'
    | '/_authenticated/settings'
    | '/_authenticated/sound-designer'
    | '/_authenticated/soundpool'
    | '/_authenticated/studio'
    | '/_authenticated/studio-bench'
    | '/_authenticated/wizard'
    | '/api/transcribe'
    | '/_authenticated/admin/fx-review'
    | '/_authenticated/fx/$fxId'
    | '/_authenticated/fx/upload'
    | '/_authenticated/parties/$partyId'
    | '/_authenticated/parties/new'
    | '/_authenticated/settings_/audio'
    | '/api/ai/party-host-speak'
    | '/p/$partyId/guest'
    | '/_authenticated/fx/'
    | '/api/public/hooks/storage-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VisualizerRoute: typeof VisualizerRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiAiPartyHostSpeakRoute: typeof ApiAiPartyHostSpeakRoute
  PPartyIdGuestRoute: typeof PPartyIdGuestRoute
  ApiPublicHooksStorageCleanupRoute: typeof ApiPublicHooksStorageCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wizard': {
      id: '/_authenticated/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof AuthenticatedWizardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio-bench': {
      id: '/_authenticated/studio-bench'
      path: '/studio-bench'
      fullPath: '/studio-bench'
      preLoaderRoute: typeof AuthenticatedStudioBenchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/soundpool': {
      id: '/_authenticated/soundpool'
      path: '/soundpool'
      fullPath: '/soundpool'
      preLoaderRoute: typeof AuthenticatedSoundpoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sound-designer': {
      id: '/_authenticated/sound-designer'
      path: '/sound-designer'
      fullPath: '/sound-designer'
      preLoaderRoute: typeof AuthenticatedSoundDesignerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remix': {
      id: '/_authenticated/remix'
      path: '/remix'
      fullPath: '/remix'
      preLoaderRoute: typeof AuthenticatedRemixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/party-host': {
      id: '/_authenticated/party-host'
      path: '/party-host'
      fullPath: '/party-host'
      preLoaderRoute: typeof AuthenticatedPartyHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moments': {
      id: '/_authenticated/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AuthenticatedMomentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lyric-writer': {
      id: '/_authenticated/lyric-writer'
      path: '/lyric-writer'
      fullPath: '/lyric-writer'
      preLoaderRoute: typeof AuthenticatedLyricWriterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loops': {
      id: '/_authenticated/loops'
      path: '/loops'
      fullPath: '/loops'
      preLoaderRoute: typeof AuthenticatedLoopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karaoke': {
      id: '/_authenticated/karaoke'
      path: '/karaoke'
      fullPath: '/karaoke'
      preLoaderRoute: typeof AuthenticatedKaraokeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crowd': {
      id: '/_authenticated/crowd'
      path: '/crowd'
      fullPath: '/crowd'
      preLoaderRoute: typeof AuthenticatedCrowdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cockpit': {
      id: '/_authenticated/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof AuthenticatedCockpitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choir': {
      id: '/_authenticated/choir'
      path: '/choir'
      fullPath: '/choir'
      preLoaderRoute: typeof AuthenticatedChoirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle': {
      id: '/_authenticated/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof AuthenticatedBattleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autotune': {
      id: '/_authenticated/autotune'
      path: '/autotune'
      fullPath: '/autotune'
      preLoaderRoute: typeof AuthenticatedAutotuneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-lab': {
      id: '/_authenticated/ai-lab'
      path: '/ai-lab'
      fullPath: '/ai-lab'
      preLoaderRoute: typeof AuthenticatedAiLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fx/': {
      id: '/_authenticated/fx/'
      path: '/fx'
      fullPath: '/fx/'
      preLoaderRoute: typeof AuthenticatedFxIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/p/$partyId/guest': {
      id: '/p/$partyId/guest'
      path: '/p/$partyId/guest'
      fullPath: '/p/$partyId/guest'
      preLoaderRoute: typeof PPartyIdGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/party-host-speak': {
      id: '/api/ai/party-host-speak'
      path: '/api/ai/party-host-speak'
      fullPath: '/api/ai/party-host-speak'
      preLoaderRoute: typeof ApiAiPartyHostSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings_/audio': {
      id: '/_authenticated/settings_/audio'
      path: '/settings/audio'
      fullPath: '/settings/audio'
      preLoaderRoute: typeof AuthenticatedSettingsAudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parties/new': {
      id: '/_authenticated/parties/new'
      path: '/parties/new'
      fullPath: '/parties/new'
      preLoaderRoute: typeof AuthenticatedPartiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parties/$partyId': {
      id: '/_authenticated/parties/$partyId'
      path: '/parties/$partyId'
      fullPath: '/parties/$partyId'
      preLoaderRoute: typeof AuthenticatedPartiesPartyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fx/upload': {
      id: '/_authenticated/fx/upload'
      path: '/fx/upload'
      fullPath: '/fx/upload'
      preLoaderRoute: typeof AuthenticatedFxUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fx/$fxId': {
      id: '/_authenticated/fx/$fxId'
      path: '/fx/$fxId'
      fullPath: '/fx/$fxId'
      preLoaderRoute: typeof AuthenticatedFxFxIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fx-review': {
      id: '/_authenticated/admin/fx-review'
      path: '/admin/fx-review'
      fullPath: '/admin/fx-review'
      preLoaderRoute: typeof AuthenticatedAdminFxReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/storage-cleanup': {
      id: '/api/public/hooks/storage-cleanup'
      path: '/api/public/hooks/storage-cleanup'
      fullPath: '/api/public/hooks/storage-cleanup'
      preLoaderRoute: typeof ApiPublicHooksStorageCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiLabRoute: typeof AuthenticatedAiLabRoute
  AuthenticatedAutotuneRoute: typeof AuthenticatedAutotuneRoute
  AuthenticatedBattleRoute: typeof AuthenticatedBattleRoute
  AuthenticatedChoirRoute: typeof AuthenticatedChoirRoute
  AuthenticatedCockpitRoute: typeof AuthenticatedCockpitRoute
  AuthenticatedCrowdRoute: typeof AuthenticatedCrowdRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKaraokeRoute: typeof AuthenticatedKaraokeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedLoopsRoute: typeof AuthenticatedLoopsRoute
  AuthenticatedLyricWriterRoute: typeof AuthenticatedLyricWriterRoute
  AuthenticatedMomentsRoute: typeof AuthenticatedMomentsRoute
  AuthenticatedPartyHostRoute: typeof AuthenticatedPartyHostRoute
  AuthenticatedRemixRoute: typeof AuthenticatedRemixRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSoundDesignerRoute: typeof AuthenticatedSoundDesignerRoute
  AuthenticatedSoundpoolRoute: typeof AuthenticatedSoundpoolRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedStudioBenchRoute: typeof AuthenticatedStudioBenchRoute
  AuthenticatedWizardRoute: typeof AuthenticatedWizardRoute
  AuthenticatedAdminFxReviewRoute: typeof AuthenticatedAdminFxReviewRoute
  AuthenticatedFxFxIdRoute: typeof AuthenticatedFxFxIdRoute
  AuthenticatedFxUploadRoute: typeof AuthenticatedFxUploadRoute
  AuthenticatedPartiesPartyIdRoute: typeof AuthenticatedPartiesPartyIdRoute
  AuthenticatedPartiesNewRoute: typeof AuthenticatedPartiesNewRoute
  AuthenticatedSettingsAudioRoute: typeof AuthenticatedSettingsAudioRoute
  AuthenticatedFxIndexRoute: typeof AuthenticatedFxIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiLabRoute: AuthenticatedAiLabRoute,
  AuthenticatedAutotuneRoute: AuthenticatedAutotuneRoute,
  AuthenticatedBattleRoute: AuthenticatedBattleRoute,
  AuthenticatedChoirRoute: AuthenticatedChoirRoute,
  AuthenticatedCockpitRoute: AuthenticatedCockpitRoute,
  AuthenticatedCrowdRoute: AuthenticatedCrowdRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKaraokeRoute: AuthenticatedKaraokeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedLoopsRoute: AuthenticatedLoopsRoute,
  AuthenticatedLyricWriterRoute: AuthenticatedLyricWriterRoute,
  AuthenticatedMomentsRoute: AuthenticatedMomentsRoute,
  AuthenticatedPartyHostRoute: AuthenticatedPartyHostRoute,
  AuthenticatedRemixRoute: AuthenticatedRemixRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSoundDesignerRoute: AuthenticatedSoundDesignerRoute,
  AuthenticatedSoundpoolRoute: AuthenticatedSoundpoolRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedStudioBenchRoute: AuthenticatedStudioBenchRoute,
  AuthenticatedWizardRoute: AuthenticatedWizardRoute,
  AuthenticatedAdminFxReviewRoute: AuthenticatedAdminFxReviewRoute,
  AuthenticatedFxFxIdRoute: AuthenticatedFxFxIdRoute,
  AuthenticatedFxUploadRoute: AuthenticatedFxUploadRoute,
  AuthenticatedPartiesPartyIdRoute: AuthenticatedPartiesPartyIdRoute,
  AuthenticatedPartiesNewRoute: AuthenticatedPartiesNewRoute,
  AuthenticatedSettingsAudioRoute: AuthenticatedSettingsAudioRoute,
  AuthenticatedFxIndexRoute: AuthenticatedFxIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VisualizerRoute: VisualizerRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiAiPartyHostSpeakRoute: ApiAiPartyHostSpeakRoute,
  PPartyIdGuestRoute: PPartyIdGuestRoute,
  ApiPublicHooksStorageCleanupRoute: ApiPublicHooksStorageCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
